export const ACTIONS = {
    SIGN_IN : "SIGN_IN",
    SIGN_IN_FAILED : "SIGN_IN_FAILED",
    SIGN_UP : "SIGN_UP",
    SIGN_UP_FAILED : "SIGN_UP_FAILED",
    DISCOVERY_MOVIE : "DISCOVERY_MOVIE",
    DISCOVERY_MOVIE_FAILED : "DISCOVERY_MOVIE_FAILED",
    TRAILER : 'TRAILER',
    TRAILER_FAILED : 'TRAILER',
    SEARCH_TRAILER : 'SEARCH_TRAILER',
    SEARCH_TRAILER_FAILED : 'SEARCH_TRAILER_FAILED'
}